### ISSUE TITLE
Globals are not being loaded using ZPM

### ISSUE THREAD

**Issue by evshvarov** [henryhamon/pop-song-analytics#3]
https://github.com/henryhamon/pop-song-analytics/blob/3635cc0dbd676610d56031daeb9b797f9c066cb9/src/gbl/dc.bi.pop-songs-globals.xml
globals cannot be loaded via 
https://github.com/henryhamon/pop-song-analytics/blob/3635cc0dbd676610d56031daeb9b797f9c066cb9/module.xml
because module.xml expects every global in a new file.
You either can list both globals, data, and index, in the repository, or rebuild indexes after importing only the data global.

**Comment by henryhamon** [comment]
thanks for advising me
